<a href="https://colab.research.google.com/github/aslla77/practice-Python/blob/main/basic/15_Back_ReLU_sigmoid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ReLU 함수

$$ h(x)=\begin{cases} x (x>0) \\ 0 (x \le 0) \end {cases} $$

$$ y = {\left\vert x \right\vert + x \over 2}$$

0이상이면 입력값을 그대로 출력 입력이 0 이하면 0으로 출력

###복습
####계단 함수 (step function)

$$ y= {\left\vert x \right\vert + x \over 2x} $$

값이 1또는 0 밖에 출력이 되지 않는다 

####시그모이드 함수 (sigmoid function)

$$ y= {1 \over 1+ e^{-x}} $$

반복적으로 계산할 수록 0으로 수렴 

#ReLU 의 미분

$$ h(x)=\begin{cases} x (x>0) \\ 0 (x \le 0) \end {cases} $$

$$ {\partial y \over \partial x} =\begin{cases} 1 (x>0) \\ 0 (x \le 0) \end {cases}$$

들어온 값이 x가 0보다 작은지 검사

작으면 0 으로 처리 

방법 1. if문으로 처리 (단이 값)
방법 2. mask를 사용하여 처리

In [1]:
import numpy as np


In [4]:
xcopy=np.array([[1,-2],[-3,2]])

mask=(xcopy<=0)
print( 'mask:',mask)

xcopy[mask]=0 #처리
print(xcopy)

mask: [[False  True]
 [ True False]]
[[1 0]
 [0 2]]


In [5]:
#ReLU의 역전파

class ReLU:
  def __init__(self):
     self.mask=None

  def forword(self,x):
    self.mask=(x<=0)
    out=x.copy()
    out[self.mask]=0
    return out

  def backword(self,dout):
    dout[self.mask]=0
    dx=dout
    return dx

In [16]:
x=np.array([[1,-2],[-3,2]])
mask=(x<0)
print(mask)

ReLU_Layer=ReLU()
out=ReLU_Layer.forword(x)
print(out)

[[False  True]
 [ True False]]
[[1 0]
 [0 2]]


In [15]:
x_1=np.ones((2,2))
dout=ReLU_Layer.backword(x_1)
print(dout) 

[[1. 0.]
 [0. 1.]]


#sigmoid 의 역전파 
###밑의 결과 값을 단순화 하여 순전파의 출력만으로 구성 가능하게 바꿀 것
$$ {\partial L \over \partial y}y^2exp(-x) $$

$$y={1 \over 1+ exp(-x}$$

y값을 치환

$$ {\partial L \over \partial y}{1 \over (1+ exp(-x))^2}exp(-x) $$

$$ {\partial L \over \partial y}{1 \over 1+ exp(-x)}{exp(-x) \over 1+ exp(-x)} $$

정히하면 

$${\partial L \over \partial y}y(1-y)$$

In [36]:
#Sigmoid의 역전파

class sigmoid:
  def __init__(self):
    self.y=None
    pass
  def forword(self,x):
    self.y=1/(1+np.exp(-x))

    return 1/(1+np.exp(-x))

  def backword(self,dout):
    dx=dout*(1.0-self.y)*self.y
    return dx
  

In [39]:
sigmoid_Layer=sigmoid()

x=np.array([[1,5],[10,20]])

ans=sigmoid_Layer.forword(x)
print(ans)

[[0.73105858 0.99330715]
 [0.9999546  1.        ]]


In [40]:
dout=1
dout=sigmoid_Layer.backword(dout)
print(dout)

[[1.96611933e-01 6.64805667e-03]
 [4.53958077e-05 2.06115369e-09]]
