<a href="https://colab.research.google.com/github/aslla77/practice-Python/blob/main/basic/6_3_layer_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

행렬 , 연립방정식 이용하여 머신러닝에서의 행렬

3층신경망의 구현

In [2]:
import numpy as np

In [5]:
X=np.array([0,0,1])
W1=np.array([[2,2,-1],[2,2,0],[0,-1,-1]])
W2=np.array([[2,2,-1],[-1,0,0],[2,-1,2]])
W3=np.array([[2,-1,-0],[-1,-1,0],[2,0,0]])

#오른쪽 부터 실햄되는 중
Y=np.dot(W3,np.dot(W2,np.dot(W1,X)))

print(Y)

[-3  0 -2]


In [6]:
#가운데 부터 실행되는 중
Y=np.dot(np.dot(np.dot(W3,W2),W1),X)

print(Y)

[-3  0 -2]


In [7]:
#입력과 히든레이어 1층 까지

def sigmoid(x):
  return 1/(1+np.exp(-x))

#데이터 설정
X=np.array([1.0,0.5])             #2

W1=np.array([[0.1,0.3,0.5],
             [0.2,0.4,0.6]])       #2x3

B1=np.array([0.1,0.2,0.3])         #3

#입력후 시그모이드로 판별까지
A1=np.dot(X,W1)+B1              #1x2 *2x3 >>1x3
Z1=sigmoid(A1)

print(Z1)


[0.57444252 0.60587367 0.75026011]


In [13]:
#1층에서 2층 

W2=np.array([[0.1,0.4],
            [0.2,0.5],
            [0.3,0.6]])       #3x2
B2=np.array([0.1,0.2])        #2

A2=np.dot(Z1,W2)+B2
Z2=sigmoid(A2)             #1x3 *3*x >>1x2

print(A2)
print(Z2)

[0.50369702 1.1828699 ]
[0.62332775 0.76546343]


시그모이드 함수의 문제가 발생 

0과 1 사이로만 표시 하기에 입력값의 크기에 따라서 데이터값을 표기하기 힘들다.

그래서 나타난 ReLU함수

In [16]:
#2층에서 출력층까지

def iden(x):
  return x

W3=np.array([[0.1,0.3],
             [0.2,0.4]])
B3=np.array([ 0.1,0.2])

A3=np.dot(Z2,W3)+B3
Y=iden(A3)

print(Y)

[0.31542546 0.6931837 ]


In [20]:
def init_network():
  network={}
  network['W1']=np.array([[0.1,0.3,0.5], [0.2,0.4,0.6]]) 
  network['B1']=np.array([0.1,0.2,0.3]) 
  network['W2']=np.array([[0.1,0.4],[0.2,0.5], [0.3,0.6]])
  network['B2']=np.array([0.1,0.2]) 
  network['W3']=np.array([[0.1,0.3],[0.2,0.4]])
  network['B3']=np.array([ 0.1,0.2])
  return network

def forword(network,x):
  W1,W2,W3=network['W1'],network['W2'],network['W3']
  b1,b2,b3=network['B1'],network['B2'],network['B3']
  a1=np.dot(x,W1)+b1
  z1=sigmoid(a1)
  a2=np.dot(z1,W2)+b2
  z2=sigmoid(a2)
  a3=np.dot(z2,W3)+b3
  y=iden(a3)
  return y

network=init_network()
x=np.array([1.0,0.5])
y=forword(network,x)

print(y)

[0.31682708 0.69627909]
