<a href="https://colab.research.google.com/github/aslla77/practice-Python/blob/main/2nd/01_About_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#About Lambda

In [27]:
f= lambda x :x+100

for i in range(3):
  print(f(i))

#수치미분 이나 활성화 함수등을 표현할 때 사용된다

100
101
102


In [2]:
def hello():
  print('hello')

def test(s,t):
  print(s,t)

s=100
t=200

fx=lambda x,y:test(s,t)
fy=lambda x,y:hello()

fx(500,600)
fy(300,600)

100 200
hello


#with 구문 

f= open('파일 주소','w')
f.write('asdasd')
f.close()

를 with 함수를 사용하면

with open("파일 주소",'w') as f
  f.write('asdasd')

로 짧게 변환이 가능하다

딥러닝 프레임 워크인 TensorFlow 의 session을 사용시 자주 사용됨

In [3]:
import numpy as np

In [18]:
A=np.array([1,2,3])
B=np.array([[1,2,3],[4,5,6]])


print(A.shape,B.shape,'\n') #행렬의 형태
print(A.ndim,B.ndim,'\n') #차원

print(B,'\n')
print(B.reshape(3,2).shape,'\n')
print(B.reshape(3,2),'\n')


(3,) (2, 3) 

1 2 

[[1 2 3]
 [4 5 6]] 

(3, 2) 

[[1 2]
 [3 4]
 [5 6]] 

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [22]:
#np.dot으로 혁과값을 다양하게 만들수 있다
#dot은 머신러닝과 이미지 프로세싱 분야에서 자주 사용된다.
print(A.shape, B.T.shape)
print(np.dot(A,B.T))

print(np.dot(A,B))#배열이 맞지 않아서 실행이 되지 않는다

(3,) (3, 2)
[14 32]


ValueError: ignored

In [23]:
#broadcast는 행렬이 맞지 않아도 사용이 되게 바꾸어 준다.
#이러한 기능 사칙연산에서만 가능해진다.

print(A+5)
#위와 같은 경우는 [5,5,5]로 만들어서 덧셈 실행

[6 7 8]


In [25]:
#전치 행렬
#행과렬을 바꾸어준다
print(B.T)
print(B.T.shape)

#백터는 열과 행을 가지지 않아 전치해도 같다
print(A.shape)
print(A.T.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)
(3,)
(3,)


In [29]:
#iterator
A_1=np.array([[10,20,30,40],[50,60,70,80]])

it=np.nditer(A_1,flags=['multi_index'],op_flags=['readwrite'])

while not it.finished:
  index=it.multi_index
  print(index)
  print('Current==',A_1[index])
  it.iternext()

(0, 0)
Current== 10
(0, 1)
Current== 20
(0, 2)
Current== 30
(0, 3)
Current== 40
(1, 0)
Current== 50
(1, 1)
Current== 60
(1, 2)
Current== 70
(1, 3)
Current== 80


In [39]:
A_2=np.array([[10,20,30],[40,50,60]])
row=np.array([70,80,90]).reshape(1,3)
column=np.array([1000,2000]).reshape(2,1)

A_3=np.concatenate((A_2,row),axis=0)
A_4=np.concatenate((A_2,column),axis=1)

print(A_3.shape,'\n',A_3,'\n')
print(A_4.shape,'\n',A_4,'\n')

#머신러닝 회귀(regression) 코드 구현시 가중치와 바이어스 를 별도로 구분하지 않고 하나의 행렬로 취급을 하기위한 프로그래밍 구현하기 위한 기술

(3, 3) 
 [[10 20 30]
 [40 50 60]
 [70 80 90]] 

(2, 4) 
 [[  10   20   30 1000]
 [  40   50   60 2000]] 



#numpy.loadtxt()

(,)로 구분된 데이터를 read하기 위한 함수
리턴은 행렬이다

머신러닝 코드에서 입력과 정답 데이터를 분리 하는 기법