<a href="https://colab.research.google.com/github/aslla77/practice-Python/blob/main/2nd/10_Tensorflow_(1xx_version).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TensorFlow 의 1.xx버전 공부 내용이므로 생략

#TensorFlow의 기초 

####텐서를 흘려보내면서 머신러닝과 딥러닝 알고리즘을 수행하는 라이브러리임

- 숫자 1 (스칼라 또는 rank 0 텐서)
- 1차원 배열 [1,2] (벡터 또는 rank 1 텐서)
- 2차원 배열 [[1,2],[3,4]] (행렬 또는 rank 2 텐서)
- 3차원 배열 [[[1,2],[3,4]]] (텐서 또는 rank 3 첸서)

####이러한 텐서들은 그래프(Graph)구조에서 노드(Node)에서 노드로 흘러감(Flow)
- 그래프 자료 구조는 노드(Node)와 엣지(Edge)로 구성됨
-텐서플로를 이용한 프로그램 작성시,

1. 상수,변수,텐서연산 등의 노드와 엣지를 먼저 정의하고,
2. 세선을 만들고 그 세션을 통해 노드간의 데이터(텐서) 연산 수행

##상수 노드

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
a=tf.constant(1.0,name='a')
b=tf.constant(2.0,name='b')
c=tf.constant([[1.0,2.0],[3.0,4.0]])

print(a)
print(a+b)
print(c)

tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


#Session
sess=tf.Session()을 만드는 경우가 있는데 tensorflow의 버젼의 차이로 생기게된다.

버전 차이로 인한 내용
- 2.xx version은 앞에 tf를 하게 된다.

In [ ]:
print(([a,b]))
print((c))
print((c+1.0))

tf.print(([a,b]))
tf.print((c)) 
tf.print(([a+b]))
tf.print((c+1.0))

[<tf.Tensor: shape=(), dtype=float32, numpy=1.0>, <tf.Tensor: shape=(), dtype=float32, numpy=2.0>]
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)
[1, 2]
[[1 2]
 [3 4]]
[3]
[[2 3]
 [4 5]]


#placeholder 

보통은 입력데이터,정답데이터 등을 넣어주기위한 용도

- placeholder 또한 사라진 형태이다

그냥 함수를 만들어서 입력값을 받는 형태로 변경

In [ ]:
# a=tf.placeholder(tf.float32)
# b=tf.placeholder(tf.float32)
# c=a+b
# tf.print(c,feed_dict={a:1.0,b:3.0})
# tf.print(c,feed_dict={a:[1.0,2.0],b:[3.0,4.0]})

# d=100*c

@tf.function
def add(x,y):
  return x+y

print('일반 프린트 시와 세션런을 이용했을 시')

A=tf.constant(1.0)
B=tf.constant(3.0)

print(add(A,B))
tf.print(add(A,B),'\n')

A=tf.constant([1.0,2.0])
B=tf.constant([3.0,4.0])

print(add(A,B))
tf.print(add(A,B),'\n')

A=tf.constant([[1.0,2.0],[3.0,4.0]])
B=tf.constant([[5.0,6.0],[7.0,8.0]])
print(add(A,B))
tf.print(add(A,B),'\n')



일반 프린트 시와 세션런을 이용했을 시
tf.Tensor(4.0, shape=(), dtype=float32)
4 



tf.Tensor([4. 6.], shape=(2,), dtype=float32)
[4 6] 



tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
[[6 8]
 [10 12]] 



#Variable 노드

2.xx버전에서는 
- tf.random_normal 또한 tf.random.normal로 변경

In [ ]:
W1=tf.Variable(tf.random.normal([1]))
b1=tf.Variable(tf.random.normal([1]))

W2=tf.Variable(tf.random.normal([1,2]))
b2=tf.Variable(tf.random.normal([1,2]))

for step in range(3):
  W1=W1-step
  b1=b1-step
  W2=W2-step
  b2=b2-step
  tf.print('step:',step,'W1=',W1,'b1=',b1)
  tf.print('step:',step,'W2=',W2,'b1=',b2,'\n')

step: 0 W1= [-0.559985936] b1= [-1.13634324]
step: 0 W2= [[-0.399875373 -0.493840277]] b1= [[-1.33573163 0.575312495]] 

step: 1 W1= [-1.55998588] b1= [-2.13634324]
step: 1 W2= [[-1.3998754 -1.49384022]] b1= [[-2.33573151 -0.424687505]] 

step: 2 W1= [-3.55998588] b1= [-4.136343]
step: 2 W2= [[-3.3998754 -3.49384022]] b1= [[-4.33573151 -2.42468739]] 



#Linear Regression with TF
###loss , optimizer 개념



In [ ]:
load_data=np.loadtxt('/content/drive/MyDrive/data-01.csv',delimiter=',')
x_data=load_data[:,0:-1].astype(np.float32)
t_data=load_data[:,[-1]].astype(np.float32)

In [ ]:
W=tf.Variable(tf.random.normal([3,1]),tf.float64)
b=tf.Variable(tf.random.normal([1]),tf.float64)
learning_rate=1e-3

@tf.function
def dotclass(x):
  y=tf.matmul(x,W)+b
  return y

@tf.function
def loss(x,t):
  loss=tf.reduce_mean(tf.square(dotclass(x)-t),0)
  return loss

@tf.function
def train(x,t):
  optimizer=tf.optimizers.SGD(learning_rate)
  train=optimizer.minimize(loss(x,t))
  return train

In [ ]:
for step in range(8001):
  loss_val =loss(x_data,t_data)
  y_val=dotclass(x_data)
  _=train(x_data,t_data)
  if step%400==0:
    tf.print('step=',step,", loss_val=",loss_val)

TypeError: ignored