<a href="https://colab.research.google.com/github/aslla77/practice-Python/blob/main/SuanLab/About_Numpy/_NumPy_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [3]:
import numpy as np
np.__version__

'1.21.6'



---



## 배열 생성

### 리스트로 배열 만들기


In [4]:
a1=np.array([1,2,3])
print(a1)
print(type(a1))
print(a1.shape)
print(a1.dtype)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
int64


In [5]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[1,2,3],[4,5,6],[7,8,9]],
             [[1,2,3],[4,5,6],[7,8,9]]])
print(a3)
print(a3.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

* `ones()`: 모든 요소를 1로 초기화

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [9]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [11]:
tri=np.tri(3)
print(tri,'\n\n',tri.T)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]] 

 [[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]


* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [12]:
np.empty(10)

array([1.90232111e-316, 1.77863633e-322, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 1.60094238e+160, 2.10653140e-052, 5.49433381e-090,
       7.86931376e-067, 4.34177643e-315])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [13]:
np.zeros_like(a1)

array([0, 0, 0])

In [14]:
np.ones_like(a2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [15]:
np.full_like(a3,10)

array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [17]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [18]:
np.logspace(0,10,5)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [19]:
np.random.random((3,3))

array([[0.44909918, 0.91056718, 0.22360636],
       [0.66726351, 0.51181488, 0.72337128],
       [0.57152816, 0.29932837, 0.22439701]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [20]:
np.random.randint(0,10,(3,3))

array([[4, 1, 5],
       [4, 0, 0],
       [0, 5, 9]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [21]:
np.random.normal(0,1,(3,3))

array([[-1.80622928,  1.68539002,  0.54318077],
       [ 1.00346276,  2.52633167, -0.11172889],
       [-1.28491797,  0.41893558,  0.7418011 ]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [22]:
np.random.rand(10)

array([0.66638615, 0.99169228, 0.7514298 , 0.66369671, 0.69011397,
       0.15783292, 0.21194114, 0.14252103, 0.10833926, 0.0323293 ])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [23]:
np.random.randn(10)

array([-0.31201464, -0.43088231,  1.63981547, -0.54953207, -0.29892308,
        2.03745107, -0.40539251, -0.65559785, -1.52050063, -1.64334547])

### 표준 데이터 타입

In [24]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [26]:
np.full((3,3),1.0,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [27]:
date=np.array('2022-08-26',dtype=np.datetime64)
date

array('2022-08-26', dtype='datetime64[D]')

In [28]:
date+np.arange(12)

array(['2022-08-26', '2022-08-27', '2022-08-28', '2022-08-29',
       '2022-08-30', '2022-08-31', '2022-09-01', '2022-09-02',
       '2022-09-03', '2022-09-04', '2022-09-05', '2022-09-06'],
      dtype='datetime64[D]')

In [29]:
datetime=np.datetime64('2022-08-26 12:00')
datetime

numpy.datetime64('2022-08-26T12:00')

In [30]:
datetime=np.datetime64('2022-08-26 12:00:12.34','ns')
datetime

numpy.datetime64('2022-08-26T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [31]:
def array_info(array):
  print(array)
  print('ndim:',array.ndim)
  print('shape:',array.shape)
  print('dtype:',array.dtype)
  print('size:',array.size)
  print('items:',array.itemsize) #각하나가 8byte를 가지고 있다
  print('nbyte:',array.nbytes)   #전체 byte의 크기
  print('strides:',array.strides)#다음차원으로 넘어가기 위한 단위 0인덱스에서 2인데스로


In [32]:
array_info(a1)

[1 2 3]
ndim: 1
shape: (3,)
dtype: int64
size: 3
items: 8
nbyte: 24
strides: (8,)


In [33]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
items: 8
nbyte: 72
strides: (24, 8)


In [34]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int64
size: 27
items: 8
nbyte: 216
strides: (72, 24, 8)


### 인덱싱(Indexing)

In [35]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-2])

[1 2 3]
1
3
3
2


In [36]:
print(a2)
print(a2[0,0])
print(a2[2,2])
print(a2[-1,1])
print(a2[-2,-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
8
6


In [37]:
print(a3)
print(a3[0,0,0])
print(a3[2,2,2])
print(a3[-1,-1,-1])
print(a3[-2,-2,0])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
9
9
4


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [38]:
print(a1)
print(a1[0:2])
print(a1[::-1])
print(a1[::2])

[1 2 3]
[1 2]
[3 2 1]
[1 3]


In [39]:
print(a2)
print(a2[1])
print(a2[1,:])
print(a2[:2,:2])
print(a2[1:,::-1])
print(a2[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [40]:
print(a1)
bi=[False,True,True]
print(a1[bi])
print(a1[a1>2])

[1 2 3]
[2 3]
[3]


In [41]:
print(a2)
bi=np.random.randint(0,2,(3,3),dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False  True]
 [False  True False]
 [False  True  True]]
[3 5 8 9]


### 팬시 인덱싱(Fancy Indedxing)

In [42]:
print(a1)
print([a1[0],a1[2]])
idx=[0,2]
print(a1[idx])

ind=np.array([[0,1],
             [2,0]])

print(a1[ind])

[1 2 3]
[1, 3]
[1 3]
[[1 2]
 [3 1]]


In [43]:
print(a2)
row=np.array([0,2])
col=np.array([1,2])

print(a2[row,col])
print(a2[row,:])
print(a2[:,col])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [44]:
print(a1)

b1=np.insert(a1,0,10)

print(b1)
print(a1)

x1=np.insert(a1, 1,10)
print(x1)

[1 2 3]
[10  1  2  3]
[1 2 3]
[ 1 10  2  3]


In [45]:
print(a2)

b2=np.insert(a2,1,10,axis=0)
c2=np.insert(a2,1,10,axis=1)
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [46]:
print(a1)


a1[:1]=9
print(a1)

i=np.array([1,2])
a1[i]=9
print(a1)

[1 2 3]
[9 2 3]
[9 9 9]


In [47]:
print(a2)
a2[0,0]=1
a2[1,1]=2
a2[2,2]=3
a2[0]=1
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [48]:
a1=np.arange(1,6,1)
print(a1)
b1=np.delete(a1,1)
print(b1)

[1 2 3 4 5]
[1 3 4 5]


In [49]:
print(a2)
b2=np.delete(a2,1,axis=0)
print(b2)
c2=np.delete(a2,1,axis=1)
print(c2)

[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [7 8 3]]
[[1 1]
 [4 6]
 [7 3]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [50]:
print(a2)

print(a2[:2,:2])

a2_sub=a2[:2,:2]
print(a2_sub)
a2_sub[:,1]=0
print(a2) #원본 배열도 0으로 바뀌어 버렸다 그래서 리스트 자료형과 다르다는 것


[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1]
 [4 2]]
[[1 1]
 [4 2]]
[[1 0 1]
 [4 0 6]
 [7 8 3]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [51]:
print(a2)
a2_sub_copy=a2[:2,:2].copy()
print(a2_sub_copy)

a2_sub_copy[:,1]=1
print(a2_sub_copy)
print(a2) #복사되어 다른 값이 되지 않는다

[[1 0 1]
 [4 0 6]
 [7 8 3]]
[[1 0]
 [4 0]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 0 6]
 [7 8 3]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [52]:
print(a2)

print(a2.T)

[[1 0 1]
 [4 0 6]
 [7 8 3]]
[[1 4 7]
 [0 0 8]
 [1 6 3]]


In [53]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [54]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 6]
 [7 8 3]]
[[1 4 7]
 [0 0 8]
 [1 6 3]]


In [55]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [56]:
n1=np.arange(1,10,1)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [57]:
print(n1)

print(n1[np.newaxis,:5])
print(n1[:5,np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [58]:
n2=np.random.randint(0,10,(2,5))
print(n2)

n2.resize((5,2))
print(n2)

[[4 7 8 5 9]
 [3 2 5 4 2]]
[[4 7]
 [8 5]
 [9 3]
 [2 5]
 [4 2]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [59]:
n2.resize((5,5),refcheck=False)
print(n2)

[[4 7 8 5 9]
 [3 2 5 4 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [60]:
n2.resize((3,3),refcheck=False)
print(n2)

[[4 7 8]
 [5 9 3]
 [2 5 4]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [61]:
a2=np.arange(1,10).reshape(3,3)
print(a2)
b2=np.arange(10,19).reshape(3,3)
print(b2)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [62]:
c2=np.append(a2,b2)
print(c2)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [63]:
c2=np.append(a2,b2,axis=0)
print(c2)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [64]:
c2=np.append(a2,b2,axis=1 )
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [65]:
a1=np.array([1,3,5])
b1=np.array([2,4,6])

np.concatenate([a1,b1])

array([1, 3, 5, 2, 4, 6])

In [66]:
c1=np.array([7,8,9])

np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [67]:
a2=np.array([[1,2,3],
             [4,5,6]])

np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [68]:
a2=np.array([[1,2,3],
             [4,5,6]])

np.concatenate([a2,a2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [69]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [70]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [71]:
np.dstack([a2,a2])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [72]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [73]:
a1=np.arange(0,10)

print(a1)

b1,c1=np.split(a1,[5])
print(b1,c1)

b1,c1,d1,e1,f1=np.split(a1,[2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [74]:
a2=np.arange(1,10).reshape(3,3)

b2,c2=np.vsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [75]:
a2=np.arange(1,10).reshape(3,3)

b2,c2=np.hsplit(a2,[2])
print(b2)
print(c2)

[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [76]:
a3=np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3=np.dsplit(a3,[2])
print(b3)
print(c3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [77]:
a1=np.array([1,2,3])
print(a1)
print(a1+5)

[1 2 3]
[6 7 8]


In [78]:
a2=np.array([[1,2,3],
            [4,5,6],[7,8,9]])
print(a2)
print(a1+a2)

b2=np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1+b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [79]:
a1=np.arange(1,10)
print(a1)
#더하기
print(a1+1)
print(np.add(a1,10))
#빼기
print(a1-2)
print(np.subtract(a1,10))
#음수로 만들기
print(-a1)
print(np.negative(a1))
#곱하기
print(a1*2)
print(np.multiply(a1,2))
#나누기
print(a1/2)
print(np.divide(a1,2))
#몫 구하기 버림;
print(a1//2)
print(np.floor_divide(a1,2))
#제곱
print(a1**2)
print(np.power(a1,2))
#나머지
print(a1%2)
print(np.mod(a1,2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [80]:
a1=np.arange(1,10)
print(a1)
b1=np.random.randint(1,10, size=9)
print(b1)
print(a1+b1)
print(a1-b1)
print(a1*b1)
print(a1/b1)
print(a1//b1)
print(a1%b1)
print(a1**b1)

[1 2 3 4 5 6 7 8 9]
[2 2 4 7 4 3 9 2 6]
[ 3  4  7 11  9  9 16 10 15]
[-1  0 -1 -3  1  3 -2  6  3]
[ 2  4 12 28 20 18 63 16 54]
[0.5        1.         0.75       0.57142857 1.25       2.
 0.77777778 4.         1.5       ]
[0 1 0 0 1 2 0 4 1]
[1 0 3 4 1 0 7 0 3]
[       1        4       81    16384      625      216 40353607       64
   531441]


In [81]:
a2=np.arange(1,10).reshape(3,3)
print(a2)
b2=np.random.randint(1,10, size=9).reshape(3,3)
print(b2)
print(a2+b2)
print(a2-b2)
print(a2*b2)
print(a2/b2)
print(a2//b2)
print(a2**b2)
print(a2%b2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 7 7]
 [4 6 6]
 [3 9 1]]
[[ 4  9 10]
 [ 8 11 12]
 [10 17 10]]
[[-2 -5 -4]
 [ 0 -1  0]
 [ 4 -1  8]]
[[ 3 14 21]
 [16 30 36]
 [21 72  9]]
[[0.33333333 0.28571429 0.42857143]
 [1.         0.83333333 1.        ]
 [2.33333333 0.88888889 9.        ]]
[[0 0 0]
 [1 0 1]
 [2 0 9]]
[[        1       128      2187]
 [      256     15625     46656]
 [      343 134217728         9]]
[[1 2 3]
 [0 5 0]
 [1 8 0]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [82]:
a1=np.random.randint(-10,10,size=5)
print(a1)
print(np.absolute(a1))
print(np.abs(a1))

[-4  6 -8 -1 -6]
[4 6 8 1 6]
[4 6 8 1 6]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [83]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[-4  6 -8 -1 -6]
[16 36 64  1 36]
[       nan 2.44948974        nan        nan        nan]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 지수와 로그 함수 (Exponential and Log Function)

In [84]:
a1=np.random.randint(1,10,size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[5 2 3 4 4]
[148.4131591    7.3890561   20.08553692  54.59815003  54.59815003]
[32.  4.  8. 16. 16.]
[25  4  9 16 16]


In [85]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[5 2 3 4 4]
[1.60943791 0.69314718 1.09861229 1.38629436 1.38629436]
[2.32192809 1.         1.5849625  2.         2.        ]
[0.69897    0.30103    0.47712125 0.60205999 0.60205999]


#### 삼각 함수(Trigonometrical Function)


In [86]:
t=np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [87]:
x=[-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

- NAN안전 모드가 존재하고 있다
- NAN이 들어와도 에러가 아닌 안전한 값이 나온다.

#### sum(): 합 계산

In [88]:
a2=np.random.randint(1,10,size=(3,3))
print(a2)

print(a2.sum(),np.sum(a2))
print(a2.sum(axis=0),np.sum(a2,axis=0))
print(a2.sum(axis=1),np.sum(a2,axis=1))


[[5 3 2]
 [6 8 3]
 [5 7 7]]
46 46
[16 18 12] [16 18 12]
[10 17 19] [10 17 19]


#### cumsum(): 누적합 계산

In [89]:
print(a2)

print(np.cumsum(a2))
print(np.cumsum(a2,axis=0))
print(np.cumsum(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
[ 5  8 10 16 24 27 32 39 46]
[[ 5  3  2]
 [11 11  5]
 [16 18 12]]
[[ 5  8 10]
 [ 6 14 17]
 [ 5 12 19]]


#### diff(): 차분 계산

In [90]:
print(a2)

print(np.diff(a2))
print(np.diff(a2,axis=0))
print(np.diff(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
[[-2 -1]
 [ 2 -5]
 [ 2  0]]
[[ 1  5  1]
 [-1 -1  4]]
[[-2 -1]
 [ 2 -5]
 [ 2  0]]


#### prod(): 곱 계산

In [91]:
print(a2)

print(np.prod(a2))
print(np.prod(a2,axis=0))
print(np.prod(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
1058400
[150 168  42]
[ 30 144 245]


#### cumprod(): 누적곱 계산

In [92]:
print(np.cumprod(a2))
print(np.cumprod(a2,axis=0))
print(np.cumprod(a2,axis=1))

[      5      15      30     180    1440    4320   21600  151200 1058400]
[[  5   3   2]
 [ 30  24   6]
 [150 168  42]]
[[  5  15  30]
 [  6  48 144]
 [  5  35 245]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [93]:
print(a2)
b2=np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[10 10 10]
 [17 17 17]
 [19 19 19]]
[[10 10 10]
 [17 17 17]
 [19 19 19]]


#### tensordot(): 텐서곱 계산

In [94]:
print(a2)
print(b2)

print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes=0))
print(np.tensordot(a2,b2,axes=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
46
[[[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]


 [[[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]]
[[10 10 10]
 [17 17 17]
 [19 19 19]]


#### cross(): 벡터곱

In [95]:
x=[1,2,3]
y=[4,5,6]
print(np.cross(x,y))


[-3  6 -3]


#### inner()/outer(): 내적/외적

In [96]:
print(a2)
print(b2)

print(np.inner(a2,b2))
print(np.outer(a2,b2))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[10 10 10]
 [17 17 17]
 [19 19 19]]
[[5 5 5 5 5 5 5 5 5]
 [3 3 3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2 2 2]
 [6 6 6 6 6 6 6 6 6]
 [8 8 8 8 8 8 8 8 8]
 [3 3 3 3 3 3 3 3 3]
 [5 5 5 5 5 5 5 5 5]
 [7 7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7 7]]


#### mean(): 평균 계산

In [97]:
print(a2)

print(np.mean(a2))
print(np.mean(a2,axis=0))
print(np.mean(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
5.111111111111111
[5.33333333 6.         4.        ]
[3.33333333 5.66666667 6.33333333]


#### std(): 표준 편차 계산

In [98]:
print(a2)

print(np.std(a2))
print(np.std(a2,axis=0))
print(np.std(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
1.9688939051854832
[0.47140452 2.1602469  2.1602469 ]
[1.24721913 2.05480467 0.94280904]


#### var(): 분산 계산

In [100]:
print(a2)

print(np.var(a2))
print(np.var(a2,axis=0))
print(np.var(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
3.8765432098765427
[0.22222222 4.66666667 4.66666667]
[1.55555556 4.22222222 0.88888889]


#### min(): 최소값

In [101]:
print(a2)

print(np.min(a2))
print(np.min(a2,axis=0))
print(np.min(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
2
[5 3 2]
[2 3 5]


#### max(): 최대값

In [102]:
print(a2)

print(np.max(a2))
print(np.max(a2,axis=0))
print(np.max(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
8
[6 8 7]
[5 8 7]


#### argmin(): 최소값 인덱스

In [103]:
print(a2)

print(np.argmin(a2))
print(np.argmin(a2,axis=0))
print(np.argmin(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
2
[0 0 0]
[2 2 0]


#### argmax(): 최대값 인덱스

In [104]:
print(a2)

print(np.argmax(a2))
print(np.argmax(a2,axis=0))
print(np.argmax(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
4
[1 1 2]
[0 1 1]


#### median(): 중앙값

In [105]:
print(a2)

print(np.median(a2))
print(np.median(a2,axis=0))
print(np.median(a2,axis=1))

[[5 3 2]
 [6 8 3]
 [5 7 7]]
5.0
[5. 7. 3.]
[3. 6. 7.]


#### percentile(): 백분위 수



In [107]:
a1=np.array([0,1,2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='linear'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='higher'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='lower'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='nearest'))
print(np.percentile(a1,[0,20,40,60,80,100],interpolation='midpoint'))

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


#### any()

In [108]:
a2=np.array([[False,False,False],
            [False,True,True],
             [False,True,True]])
print(a2)

print(np.any(a2))
print(np.any(a2,axis=0))
print(np.any(a2,axis=1))

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


#### all()

In [112]:
a2=np.array([[False,False,True],
            [True,True,True],
             [False,True,True]])
print(a2)

print(np.all(a2))
print(np.all(a2,axis=0))
print(np.all(a2,axis=1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


### 비교 연산(Comparison Operators)


In [115]:
a1=np.arange(1,10)
print(a1)

print(a1==5)
print(a1!=5)
print(a1<5)
print(a1<=5)
print(a1>5)
print(a1>=5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True False  True  True  True  True]
[ True  True  True  True False False False False False]
[ True  True  True  True  True False False False False]
[False False False False False  True  True  True  True]
[False False False False  True  True  True  True  True]


In [118]:
a2=np.arange(1,10).reshape(3,3)
print(a2)

print(np.sum(a2))
print(np.count_nonzero(a2>5))
print(np.sum(a2>5))
print(np.sum(a2>5,axis=0))
print(np.sum(a2>5,axis=1))

print(np.any(a2>5,axis=0))
print(np.any(a2>5,axis=1))
print(np.all(a2>5,axis=0))
print(np.all(a2>5,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]
[ True  True  True]
[False  True  True]
[False False False]
[False False  True]


In [119]:
a1=np.array([1,2,3,4,5])
print(a1)
b1=np.array([1,2,3,3,4])
print(b1)

print(np.isclose(a1,b1))

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [122]:
a1=np.array([np.nan,2,np.inf,4,np.NINF])
print(a1)
print(np.isnan(a1))   #nan만 트루
print(np.isinf(a1))   #inf만 트루 음수도 가능
print(np.isfinite(a1)) #숫자만 트루

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


#### 불리언 연산자(Boolean Operators)


In [126]:
a2=np.arange(1,10).reshape(3,3)
print(a2)
#and
print((a2>5)&(a2<8))
print(a2[(a2>5)&(a2<8)])
#or
print((a2>5)|(a2<8))
print(a2[(a2>5)|(a2<8)])
#xor
print((a2>5)^(a2<8))
print(a2[(a2>5)^(a2<8)])
#not
print(~(a2>5))
print(a2[~(a2>5)])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


### 배열 정렬

In [129]:
a1=np.random.randint(1,10,size=10)
print(a1)
print(np.sort(a1))
print(a1)
print(np.argsort(a1))
print(a1)

print(a1.sort())
print(a1)

[7 9 6 9 7 7 5 6 9 8]
[5 6 6 7 7 7 8 9 9 9]
[7 9 6 9 7 7 5 6 9 8]
[6 2 7 0 4 5 9 1 3 8]
[7 9 6 9 7 7 5 6 9 8]
None
[5 6 6 7 7 7 8 9 9 9]


In [132]:
a2=np.random.randint(1,10,size=(3,3))
print(a2)

print(np.sort(a2,axis=0))
print(np.sort(a2,axis=1))

[[3 7 4]
 [6 4 8]
 [9 4 2]]
[[3 4 2]
 [6 4 4]
 [9 7 8]]
[[3 4 7]
 [4 6 8]
 [2 4 9]]


#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

In [133]:
a1=np.random.randint(1,10,size=10)
print(a1)
print(np.partition(a1,3))

[6 9 9 1 6 6 6 2 5 3]
[1 2 3 5 6 6 6 9 9 6]


In [134]:
a2=np.random.randint(1,10,size=(5,5))
print(a2)
print(np.partition(a2,3))
print(np.partition(a2,3,axis=0))
print(np.partition(a2,3,axis=1))

[[3 3 9 9 8]
 [1 7 6 6 7]
 [4 3 1 4 2]
 [3 7 7 9 3]
 [2 4 1 9 4]]
[[3 3 8 9 9]
 [6 1 6 7 7]
 [1 2 3 4 4]
 [3 3 7 7 9]
 [1 2 4 4 9]]
[[1 3 1 6 3]
 [2 3 1 4 2]
 [3 4 6 9 4]
 [3 7 7 9 7]
 [4 7 9 9 8]]
[[3 3 8 9 9]
 [6 1 6 7 7]
 [1 2 3 4 4]
 [3 3 7 7 9]
 [1 2 4 4 9]]


## 배열 입출력


In [135]:
a2=np.random.randint(1,10,size=(5,5))
print(a2)

np.save("a",a2) #바이너리 파일로 저장
!ls

[[4 5 2 5 8]
 [7 6 9 2 6]
 [7 2 9 5 8]
 [4 6 9 3 5]
 [4 4 4 5 1]]
a.npy  drive  sample_data


In [138]:
b2=np.random.randint(1,10,size=(5,5))

print(b2)

np.savez("ab",a2,b2) #여러개저장
!ls

[[2 7 5 6 7]
 [9 9 2 2 2]
 [6 4 1 9 4]
 [8 8 6 3 8]
 [9 2 2 6 3]]
ab.npz	a.npy  drive  sample_data


In [139]:
npy=np.load("a.npy")
print(npy)

[[4 5 2 5 8]
 [7 6 9 2 6]
 [7 2 9 5 8]
 [4 6 9 3 5]
 [4 4 4 5 1]]


In [141]:
npz=np.load('ab.npz')
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[4 5 2 5 8]
 [7 6 9 2 6]
 [7 2 9 5 8]
 [4 6 9 3 5]
 [4 4 4 5 1]]
[[2 7 5 6 7]
 [9 9 2 2 2]
 [6 4 1 9 4]
 [8 8 6 3 8]
 [9 2 2 6 3]]


In [142]:
print(a2)

np.savetxt('a.csv',a2,delimiter=',')
!ls

[[4 5 2 5 8]
 [7 6 9 2 6]
 [7 2 9 5 8]
 [4 6 9 3 5]
 [4 4 4 5 1]]
ab.npz	a.csv  a.npy  drive  sample_data


In [143]:
!cat a.csv

4.000000000000000000e+00,5.000000000000000000e+00,2.000000000000000000e+00,5.000000000000000000e+00,8.000000000000000000e+00
7.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00,2.000000000000000000e+00,6.000000000000000000e+00
7.000000000000000000e+00,2.000000000000000000e+00,9.000000000000000000e+00,5.000000000000000000e+00,8.000000000000000000e+00
4.000000000000000000e+00,6.000000000000000000e+00,9.000000000000000000e+00,3.000000000000000000e+00,5.000000000000000000e+00
4.000000000000000000e+00,4.000000000000000000e+00,4.000000000000000000e+00,5.000000000000000000e+00,1.000000000000000000e+00


In [144]:
csv=np.loadtxt('a.csv',delimiter=',')
print(csv)

[[4. 5. 2. 5. 8.]
 [7. 6. 9. 2. 6.]
 [7. 2. 9. 5. 8.]
 [4. 6. 9. 3. 5.]
 [4. 4. 4. 5. 1.]]


In [146]:
print(b2)
np.savetxt('b.csv',b2,delimiter=',',fmt='%.2e',header='c1,c2,c3,c4,c5')

[[2 7 5 6 7]
 [9 9 2 2 2]
 [6 4 1 9 4]
 [8 8 6 3 8]
 [9 2 2 6 3]]


In [147]:
!cat b.csv

# c1,c2,c3,c4,c5
2.00e+00,7.00e+00,5.00e+00,6.00e+00,7.00e+00
9.00e+00,9.00e+00,2.00e+00,2.00e+00,2.00e+00
6.00e+00,4.00e+00,1.00e+00,9.00e+00,4.00e+00
8.00e+00,8.00e+00,6.00e+00,3.00e+00,8.00e+00
9.00e+00,2.00e+00,2.00e+00,6.00e+00,3.00e+00


In [148]:
csv=np.loadtxt('b.csv',delimiter=',')
print(csv)

[[2. 7. 5. 6. 7.]
 [9. 9. 2. 2. 2.]
 [6. 4. 1. 9. 4.]
 [8. 8. 6. 3. 8.]
 [9. 2. 2. 6. 3.]]




---

